<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9f59db75e7c222a2e766279519073233
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TotalVoice\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TotalVoice\\' => 
        array (
            0 => __DIR__ . '/..' . '/total-voice/php-client/src',
            1 => __DIR__ . '/..' . '/total-voice/php-client/test',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9f59db75e7c222a2e766279519073233::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9f59db75e7c222a2e766279519073233::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
